version: '3.7'

services:

  percona: 
    image: percona/percona-xtradb-cluster:5.7.26
    container_name: percona
    restart: always
    environment: 
      - TZ=Asia/Shanghai
      - MYSQL_ROOT_PASSWORD=Percona123$
      - CLUSTER_NAME=pxc
      - XTRABACKUP_PASSWORD=Percona123 
    ports:
      - 3306:3306
    volumes:
      - percona_mysql:/var/lib/mysql
      - percona_log:/var/log/mysql
      - percona_data:/data
    networks: 
      - swarm_net

volumes: 
  percona_mysql: 
  percona_log: 
  percona_data: 

networks: 
  swarm_net: 
    external: true 
