version: '3.7'

services: 

  phpmyadmin: 
    image: phpmyadmin:5
    container_name: phpmyadmin
    restart: always
    ports: 
      - 80:80
    environment: 
      - PMA_ARBITRARY=1
    networks: 
      - swarm_net

networks: 
  swarm_net: 
    external: true 