version: '3.7'
services: 
  gitlab-runner:
    container_name: gitlab-runner
    image: 'gitlab/gitlab-runner:v15.2.1'
    restart: always
    privileged: true
    volumes:
      - 'data:/etc/gitlab-runner'
      - '/var/run/docker.sock:/var/run/docker.sock'
    networks: 
      - swarm_net
volumes: 
  data: 
networks: 
  swarm_net: 
    external: true 