version: '3.7'

services:

  postgres:
    image: postgres:11.4
    container_name: postgres
    restart: always
    environment: 
      TZ: Asia/Shanghai
      POSTGRES_PASSWORD: postgres_123456
    ports:
      - 5432:5432
    volumes: 
      - postgres_data:/var/lib/postgresql/data
    networks: 
      - swarm_net

volumes: 
  postgres_data:

networks: 
  swarm_net: 
    external: true 