version: '3.9'

services:
  redis-stack-server:
    image: redis/redis-stack-server:latest
    hostname: redis-stack-server-node
    networks:
      - swarm_net
    ports:
      - '6379:6379'
    volumes:
      - redis-stack-server:/data
    environment:
      - TZ=Asia/Shanghai
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '2'
          memory: '4G'
        reservations:
          memory: '500M'

volumes:
  redis-stack-server:
    external: false
networks:
  swarm_net:
    driver: overlay
    external: false