version: '3.7'

services: 

  confluence:
    image: confluence:7.4.0
    container_name: confluence
    restart: always
    environment: 
      TZ: Asia/Shanghai
    ports:
      - 8090:8090
    networks: 
      - swarm_net
    volumes:
      - data:/var/atlassian/confluence
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 2G

volumes:
  data: 

networks: 
  swarm_net: 
    external: true

# docker-compose up -d
# docker-compose down